### ISSUE TITLE
Synchronization is slow

### ISSUE THREAD

**Issue by naoki-maeda** [osagga/bitcore-node-cash#10]
Synchronization of the bitcoind block is finished.
But bitcore synchronization does not progress.
It progress about only 3% a day.
Why is it so late?Is not there a good way?
Is it a problem with the bitcoind version?
Or the original insight problem?

The specification of the server is not a problem.
I use Bitcoin ABC Daemon version v0.17.2.0-4fd0b1b
Tell me please.

**Comment by osagga** [comment]
This problem is the same as #2 (the original insight problem), for bitcore-node `v5`.
There's no solution to this yet, so I'll close this issue, please use #2 for any follow-up or discussion.

As an alternative, you can try to use bitcore-node v3 (check this [guide](https://github.com/osagga/bch-bitcore-setup)), the only downside to v3 is that it uses a slightly older Bitcoin ABC Daemon (that's slightly modified for the bitcore-node).

Also I'm currently working on writing a guide on how to setup bitcore-node [v8](https://github.com/bitpay/bitcore-node/tree/v8.0.0) with BCH (and possibly LTC), by far, the v8 node is fast at syncing, and works with the latest Bitcoin ABC Daemon (without modifications), but the downside is that it uses a slightly different API endpoints with a different output format (I'll add more info later).
